version: "3"

services:

  identity-sdk-csharp-preview-build:
    build: .
    container_name: identity-sdk-csharp-preview-build
    image: finbourne/identity-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_IDENTITY_API_URL=${FBN_BASE_API_URL}/identity
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src